[package]
name = "sys_media"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
windows = { version = "0.61.3", features = ["Media_Control"] }
windows-result = "0.3.4"
